/*
 * ESP32 Car Provisioner
 *
 * Writes Wi-Fi credentials, mDNS hostname, and car identity to NVS.
 * Flash this sketch once to provision a car, then flash the main firmware.
 * NVS data persists across firmware flashes.
 *
 * Config is generated by provision-car.sh into provisioning_config.h.
 * Do not flash this sketch without a valid provisioning_config.h present.
 */
#include <Preferences.h>
#include "provisioning_config.h"

void setup()
{
  Serial.begin(115200);
  delay(1500);

  Serial.println("=== ESP32 Car Provisioner ===");
  Serial.printf("SSID:     %s\r\n", PROV_SSID);
  Serial.printf("Hostname: %s\r\n", PROV_HOSTNAME);
  Serial.printf("Car name: %s\r\n", PROV_CAR_NAME);
  Serial.println("Writing to NVS...");

  Preferences wifi;
  wifi.begin("wifi", false);
  wifi.putString("ssid",     PROV_SSID);
  wifi.putString("password", PROV_PASSWORD);
  wifi.putString("hostname", PROV_HOSTNAME);
  wifi.end();

  Preferences car;
  car.begin("car", false);
  car.putString("name", PROV_CAR_NAME);
  car.end();

  Serial.println("=== Provisioning complete ===");
  Serial.println("Ready to flash main firmware.");
  Serial.println("Run: arduino-code/bin/flash-esp32-s3-ws.sh");
  Serial.println("  or arduino-code/bin/flash-esp32-wrover-ws.sh");
}

void loop() {}
